# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-09 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180401_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('-join_date',)},
        ),
    ]
